### ISSUE TITLE
Ratelimiting is not handled correctly

### ISSUE THREAD

**Issue by abitofevrything** [nyxx-discord/nyxx#301]
**Describe the bug**
The current ratelimit handling in nyxx does not conform with Discord's actual ratelimiting behaviour. The global ratelimit is never considered, and per-route ratelimits are not applied correctly (the bucket depends on the query parameters, when it should only depend on the route).

**To Reproduce**
Attempt to perform a large amount of requests with different parameters in a short amount of time.

**Expected behavior**
Ratelimiting should be handled correctly.

**Desktop (please complete the following information):**
 - OS: Linux
 - Dart version: 2.16
 - Nyxx version: 3.3.0-dev.0

**Additional context**
[https://discord.com/developers/docs/topics/rate-limits#rate-limits](https://discord.com/developers/docs/topics/rate-limits#rate-limits)

**Comment by NDSo** [comment]
**Proposal** 
All 100+ `HttpEndpoints` methods need to construct `HttpRequest`s  with a new `route:` param that uniquely identifies the route as described in the docs. The `HttpHandler`  then dynamically maps  which new or existing `HttpBucket` discord assigned each route to after the initial request. 

Because the assignments may be dynamic on discord's end, remember to write logic that handles route -> bucket map changes after the initial mapping.

**Comment by l7ssha** [comment]
> **Update** I have this working locally. It is a rather large change so I'm going to spend some time cleaning it up and testing it. There is potential for a lot of regression as it touches every endpoint request method.

If you have working code please start draft PR so everybody can take a look even if its not fully working at the moment
