### ISSUE TITLE
feature: Distinction between forum threads and regular threads

### ISSUE THREAD

**Issue by phorcys420** [nyxx-discord/nyxx#423]
**Is your feature request related to a problem? Please describe.**
``IThreadChannel``s do not let you know if ``it`` is a forum thread or not.

**Describe the solution you'd like**
I think the best solution would be to have both ``IThreadChannel``s and ``IForumThreadChannel``s.
Which would also allow for clear distinction for #424, rather than allowing some confusion on forum-only features.

Otherwise, an ``isForum`` property on ``IThreadChannel``s would also be welcome in case distinction is not clearly made by the API itself. (example: in Thread Create/Update events)

**Describe alternatives you've considered**
I currently check whether the parent channel is a forum channel or not, which could be avoided if this was built-in.
Because I only want to know if it is a Forum Thread, not which Forum Channel it belongs to.

**Comment by abitofevrything** [comment]
Hi,
Discord sadly provides no difference between regular threads and forum threads, they use the exact same structure when returned from the API.

Your best bet is to check if the [`parent`](https://pub.dev/documentation/nyxx/latest/nyxx/IThreadChannel/parentChannel.html) is an [`IForumChannel`](https://pub.dev/documentation/nyxx/latest/nyxx/IForumChannel-class.html).

Closing because we can't implement this.
