### ISSUE TITLE
Nyxx can't be used in the web

### ISSUE THREAD

**Issue by RandomModderJDK** [nyxx-discord/nyxx#573]
**Describe the bug**
Chrome throws a TypeError, when trying to "compile"/execute the javascript. The problematic class is [this](https://github.com/nyxx-discord/nyxx/blob/dev/lib/src/utils/flags.dart).

**To Reproduce**
1. Setup project with nyxx as dependency
2. Create web platform folder with `flutter create .`
3. Add any nyxx code, e.g. example code from the [examples](https://github.com/nyxx-discord/nyxx/blob/dev/examples)

**Expected behavior**
The Flag class should get compiled correctly and nyxx can be used in the web.

**Screenshots**
![image](https://github.com/nyxx-discord/nyxx/assets/62660085/709ea44c-5148-47da-9b22-25bf3b127eec)
![image](https://github.com/nyxx-discord/nyxx/assets/62660085/b6120a74-29d4-480d-bcee-507bdd35a38d)
![image](https://github.com/nyxx-discord/nyxx/assets/62660085/6c21d370-3bc4-4547-a671-b11207a54c47)

**Desktop (please complete the following information):**
 - Platform: Linux x64
 - Dart version: 3.1.0 stable
 - Nyxx version: 6.0.0

**Additional context**
This is my auto-generated comment on flags.dart.lib.js(the compiled javascript version):

> // Generated by DDC, the Dart Development Compiler (to JavaScript).
// Version: 3.1.0 (stable) (Tue Aug 15 21:33:36 2023 +0000) on "linux_x64"
// Module: packages/nyxx/src/utils/flags.dart
// Flags: soundNullSafety(true), enableAsserts(true)

**Comment by l7ssha** [comment]
We are not supporting browser as a target since it requires a lot of additional workarounds and maintenance for it to work

**Comment by abitofevrything** [comment]
@RandomModderJDK this looks more like a compiler bug than something on our end. Either way we do not support js as a target, as l7ssha said.

**Comment by RandomModderJDK** [comment]
Why does nyxx even use components that are not functional in the web. The discord api doesnt benefit from platform specific features in particular except from audio features. 

What would be needed to make it completely platform independent?

**Comment by abitofevrything** [comment]
Nyxx uses isolates to implement sharding, as recommended by discord, and dart:io in several places to implement helpers. We also use dart:io in the isolates to speed up decoding.

If you really want to run nyxx in the web, I can patch these out and push them to my fork that you can use from a git dependency. We will not be merging these changes, or any changes aimed only at adding web support to this repository as it complicated several aspects of the code, would probably be breaking, adds dependencies on other packages and isn't something we recommend doing anyway.

**Comment by RandomModderJDK** [comment]
That would be really kind of you

**Comment by abitofevrything** [comment]
Alright, I've made the necessary changes.

I really don't recommend using it because it disables several features (including the IgnoreExceptions and CliIntegration plugins) and restricts other parts of the API (e.g transport compression can't be used, so you'll have to choose something else when connecting to the API). Additionally I had to route all requests through a CORS proxy because Discord, sensibly, doesn't manage CORS on their API which makes browsers unable to use it.

The proxy is hosted on a cloudflare worker, and I'm making no guarantees as to its stability or longevity. If it does down, nyxx won't be able to contact the Discord API and your application will stop working. I really recommend you change this and use your own proxy that you host - and if you can do that, why not just run nyxx on that server?

Anyway, with all that said, the code can be found [here](https://github.com/abitofevrything/nyxx/tree/hack/web-support) and depended on using a `git` dependency targeting `https://github.com/abitofevrything/nyxx` and `ref: hack/web-support`.

**Comment by RandomModderJDK** [comment]
Even though this issue is closed and my requirements are basically met. I kept wondering, what mechanism uses the Discord website to interavt with the API? Is discord not following their best practices?

 I thought about sniffing the traffic from the website and just try to use this for implementation.
Is there anything against that way of implementing? Is this against the ToS of discord?

**Comment by abitofevrything** [comment]
Discord allows its own website (and only its own website) to make requests from the web using CORS. It’s only a “best practise” for bots to not run in a browser, the official website can use the API from a browser just fine because its requirements and authentication methods are different.

Sniffing the traffic from the website (which is the same traffic as the electron client emits) is actually how most of the developer documentation is made. People notice the client making a request to a new endpoint or with a new payload, and open a PR to the docs to update them to reflect that change.

I don’t know if it’s against the TOS of Discord. I still wouldn’t recommend it, as there’s no real reason to do it.
