### ISSUE TITLE
Allow customising gateway properties when Identifiy is sent.

### ISSUE THREAD

**Issue by Noxits** [nyxx-discord/nyxx#587]
**Is your feature request related to a problem? Please describe.**
Currently, [identify properties](https://github.com/nyxx-discord/nyxx/blob/dev/lib/src/gateway/shard_runner.dart#L217) are hardcoded into the codebase.
Allowing to edit these would grant fine control over some undocumented behaviour. Like replacing the `browser` property to `Discord iOS/Android` to add a mobile status for example.

**Describe the solution you'd like**
Allow editing properties.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by abitofevrything** [comment]
Hi,
nyxx only implements features officially supported by the Discord API. The Discord documentation says those fields should be representative of the library used, so that is what nyxx uses. Passing customisable values to these fields is not supported.

This is possible with minimum patching, and I've uploaded a proof of concept to the [`hack/customizable-gateway-properties`](https://github.com/abitofevrything/nyxx/tree/hack/customizable-gateway-properties) of my nyxx fork. I make no guarantees about the stability of this patch or whether it violates TOS.

I will keep that branch up to date at least for a while, but I encourage you to use your own. We will not be adding support for this to the main repo, and I won't be spending too much effort keeping that branch up to date.

Closing as unplanned.
